### PR TITLE
Minor changes to make it works in both Python 3.4 and Python 2.7

### PR DESCRIPTION
**Pull request by mmarkov**
Implemented minor changes to make it works for both Python 2 and Python3 . Tested in Python 3.4 and Python 2.7

### CODE REVIEW

**Comment by drgrib** [comment]
So the challenge here is that the change will make iteration slower in Python 2.7 if `items` is used instead of `iteritems`. I understand that `items` in Python 3 has the same behavior as `iteritems` in 2.7.

Any ideas how to make it use `iteritems` if it is 2.7 but `items` it is is 3?

**Comment by mmarkov** [comment]
Sure, it is easy  - I will do it. It make sense to keep iteritems for Python2, so real list is not created

**Comment by mmarkov** [comment]
@drgrib, I implemented iteritems for Python2 and I also added travis-ci build. If you add your account to travis-ci.org it should start automatically build all pull requests and pushes to master. 
Take a look at https://travis-ci.org/mmarkov/dotmap/jobs/80558010

**Comment by drgrib** [comment]
Damn. There are a lot more changes than I was prepared to review here. I understand that `unittest` is a standard framework, but I've never used it or many of the tools you've chosen to build into the project. I was expecting this commit to only have the `iteritems` fix.

Is there a way for me to only accept the `iteritems` and `print` related fixes for now?

**Comment by mmarkov** [comment]
@drgrib , I was so eager to help so I was a little bit carried away. Let's keep this pull request for build and unit tests ( I am still going to finish them with better coverage). 
And I will create one more with python3 and iteritems only.

**Comment by mmarkov** [comment]
@drgrib , take a look at #4 - it is cleaner, shorter and better. I am going to finish rest of unit tests and integrate coveralls in #3.

**Comment by mmarkov** [comment]
Closed in favor of #4

**Pull request closed without merging**
