### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by mmarkov**
implement Python 3 support and keep iteritems for Python 2 to avoid memory waste

### CODE REVIEW

**Comment by drgrib** [comment]
Thanks!

**Comment by mmarkov** [comment]
You are welcome, looking forward to see it published at pypi.

**Comment by drgrib** [comment]
It's there. Great introspection solution to use the right method without having to reference the Python version.

**Comment by jingles** [comment]
Wow, thanks so much for adding py3 support!!!!

**Pull request merged**
